 XXXX XXXXXXXX XXXXXX XXXXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
									XXX XXXXXXXXXXXXXXX
										XXXX
											XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXX XXXXXXXX
											XXXXXX
										XXXXX
									XXXXX
								XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
										
									XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXX
										BBB BB  BB BBBBB
											BB BBBBBBBBBBBBBBBBBBBBB	
										XXX XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXX
													XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
												XXXXXX
											XXXXX
											BBBB
											BBBBB
											BBBBBB
										XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXX
								
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXXXXX XXXXXX XXXXXX XXX