XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

									BB BBBBBBBBBBBBBBBBBBBB
									  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
									
									  BB BBBBBBBBBBBBBB B B
									
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
										BB BBBBBBBBBBBBBB B B
										  XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										BBBBB
									  BBBBB
									BBBBB
									
									BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
									  BB BBBBBBBBBBBBBB BB BBB
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBB BBB B BBBBBBBBBBBBBBBBBBBBBBB BBB BBB B BBBBBBBBBBBBBBBBBBBBBB
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBBB
									BBBBBB
									
									BB BBBBBBBBBBBBBBBB
									  BB BBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
										XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBB BBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBBB
									
									  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
									BBBBB
XXXXX