# Generated by Django 4.0.5 on 2023-06-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rfq',
            new_name='Projeler',
        ),
    ]
