# Generated by Django 4.0.5 on 2023-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_rfq_projeler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeler',
            old_name='image',
            new_name='image_alt_foto',
        ),
        migrations.AddField(
            model_name='projeler',
            name='image_ana_foto',
            field=models.ImageField(blank=True, null=True, upload_to='proje_ana_foto/'),
        ),
    ]
