# Generated by Django 4.0.5 on 2023-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_projeler_image_alt_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='image_alt_foto2',
            field=models.ImageField(blank=True, null=True, upload_to='proje_alt_foto/'),
        ),
    ]
