# Generated by Django 4.0.5 on 2023-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_alt_foto_projeler_image_alt_foto1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='Lokasyon_kısa',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
