# Generated by Django 4.0.5 on 2023-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projeler_lokasyon_bilgileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='map',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
