# Generated by Django 4.0.5 on 2023-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projeler_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeler',
            name='map',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
