# Generated by Django 4.0.5 on 2023-06-17 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_projeler_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeler',
            name='Açıklama',
            field=ckeditor.fields.RichTextField(blank=True, max_length=600),
        ),
    ]
