# Generated by Django 4.0.5 on 2023-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_projeler_açıklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
