# Generated by Django 4.0.5 on 2023-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_projeler_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='şehir',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
