# Generated by Django 4.0.5 on 2023-06-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_projeler_şehir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeler',
            old_name='şehir',
            new_name='sehir',
        ),
    ]
