# Generated by Django 4.0.5 on 2023-06-18 07:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_şehir_projeler_sehir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_basligi', models.CharField(blank=True, max_length=150)),
                ('yazi_icerigi', ckeditor.fields.RichTextField(blank=True, max_length=60000)),
                ('quote', models.CharField(blank=True, max_length=450)),
                ('blog_ana_foto', models.ImageField(blank=True, null=True, upload_to='blog_ana_foto/')),
                ('blog_alt_foto1', models.ImageField(blank=True, null=True, upload_to='blog_alt_foto/')),
                ('blog_alt_foto2', models.ImageField(blank=True, null=True, upload_to='blog_alt_foto/')),
            ],
        ),
    ]
