# Generated by Django 4.0.5 on 2023-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yazar',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
