# Generated by Django 4.0.5 on 2023-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_blog_created_at_projeler_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projeler',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
