# Generated by Django 4.0.5 on 2023-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blog_updated_at_projeler_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isimSoyisim', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=150)),
                ('Telefon', models.CharField(blank=True, max_length=50)),
                ('Konu', models.CharField(blank=True, max_length=500)),
                ('Mesaj', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
