# Generated by Django 4.0.5 on 2023-06-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_customermessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='resimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ana_foto', models.ImageField(blank=True, null=True, upload_to='proje_ana_foto/')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projeler')),
            ],
        ),
    ]
