# Generated by Django 4.0.5 on 2023-06-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_resimler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeler',
            name='image_alt_foto1',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='image_alt_foto2',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='image_alt_foto3',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='image_alt_foto4',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='image_alt_foto5',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='image_alt_foto6',
        ),
    ]
