# Generated by Django 4.0.5 on 2023-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_projeler_image_alt_foto1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resimler',
            name='image_ana_foto',
            field=models.ImageField(blank=True, null=True, upload_to='altfoto/'),
        ),
    ]
