# Generated by Django 4.0.5 on 2023-07-01 19:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_resimler_image_ana_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_basligi_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_basligi_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote_ar',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote_en',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='blog',
            name='yazi_icerigi_ar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
        migrations.AddField(
            model_name='blog',
            name='yazi_icerigi_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
        migrations.AddField(
            model_name='projeler',
            name='Açıklama_ar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
        migrations.AddField(
            model_name='projeler',
            name='Açıklama_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
        migrations.AddField(
            model_name='projeler',
            name='Lokasyon_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='Lokasyon_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='Lokasyon_kısa_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='Lokasyon_kısa_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='lokasyon_bilgileri_ar',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projeler',
            name='lokasyon_bilgileri_en',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projeler',
            name='map_ar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projeler',
            name='map_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projeler',
            name='proje_ismi_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='proje_ismi_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='sehir_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projeler',
            name='sehir_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projeler',
            name='status_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projeler',
            name='status_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projeler',
            name='video_link_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeler',
            name='video_link_en',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
