# Generated by Django 4.0.5 on 2023-07-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_blog_blog_basligi_ar_blog_blog_basligi_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeler',
            name='Lokasyon_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='Lokasyon_en',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='Lokasyon_kısa_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='Lokasyon_kısa_en',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='map_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='map_en',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='sehir_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='sehir_en',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='status_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='video_link_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='video_link_en',
        ),
    ]
