# Generated by Django 4.0.5 on 2023-07-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_projeler_status_ar_projeler_status_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeler',
            name='status_ar',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='status_en',
        ),
    ]
