# Generated by Django 4.0.5 on 2023-07-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_projeler_status_ar_remove_projeler_status_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeler',
            name='lokasyon_bilgileri',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='projeler',
            name='lokasyon_bilgileri_ar',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='projeler',
            name='lokasyon_bilgileri_en',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
