# Generated by Django 4.0.5 on 2023-07-04 08:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_projeler_lokasyon_bilgileri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeler',
            name='lokasyon_bilgileri',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
        migrations.AlterField(
            model_name='projeler',
            name='lokasyon_bilgileri_ar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
        migrations.AlterField(
            model_name='projeler',
            name='lokasyon_bilgileri_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000),
        ),
    ]
