
BBBB BBBBBB
BBBB BBBB


XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
	XXXXXX
		XXXX XXXX XXXX XXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
		XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		
		XXXX XXXX XXXXX XXX
		XXXXXXXXXXXXX X XXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX
		
		XXXX XXX XXXX XXX
		XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX
		
		XXXX XXXXXX XXXXX XXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
		XXXX XXXXXXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXXXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXX XXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXX XXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXX XXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXX XX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		
		XXXX XXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

		
	XXXXXXX
	XXXXXXX
		XXXXXXX XXXXXXXXXXXXXXX
 XXXXXXXXXX X
	 XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	 XXXXXXXXXXXX XXXXXXXX
X
XXXXX XXXX X
  XXXXXXXXXX XXXXXX
  XXXXXXX XXXXX
  
X

XXXXXXXXXXXXXXXXXX
	XXXXXXXXX XXXXXXX
X
 XXX X
	 XXXXXXXX XXXXXX
	 XXXXXXXXX XXXXXXXX
X
 XXXXXXXXXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXXXXX XXXXX
	 XXXXXXXXXXXX XXXXX
	 XXXXXXX XXXXXXXXXXX
X
 XXXXXXXXXXXXXXX X
	 XXXXXXXX XX
	 XXXXXXXXX XXXXXXXXX
	 XXXX XX
	 XXXXXX XXXX
	 XXXXXXX XXXXX
	 XXXXXXXXXXX XXXXXXX XXXXX
	 XXXXXXXXXXXX XXXXXXXX
	 XXXXXXXX XX
X
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
	 XXXXXXX XXXXX
X
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
	 XXXXXXXX XX
	 XXXXXXX XXXXXXXX
X
 XXXXXXXXXXXXXXXXXXXX X
	 XXXXX XX
	 XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XX XX XXXXX XXX XXXXXXX XX XX XX XXXXXX
X
 XXXXXXXXXXXXXXXXXXXXX X
	 XXXXXX XX
	 XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XX XX XX XXX XXXXXXX XX XX XXXXX XXXXXX
X
 XXXXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXXXXXX XX
	 XXXXX XXXX
	 XXXXXXX XXXXX
	 XXXXXXXXXX XXXXXXXXXXXXXXXXX
	 XXXXXXXXXX XX
	 XXXXXXXXXXXXXXXX XXXXX
X
 XXXXXXXXXXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXXXXXX XXXXXXXXXXXXX
	 XXXXXXXXXXXXXXX XXXX
	 XXXXXX XXXXX
	 XXXXXXX XXXXX
	 XXXXXXX X XXXXXXX
	 XXXXXXXXXXXXXX XXXX
	 XXXXXXX XXX XXXXX XXXXX
	 XXXXXXX XXXXXXXX
X
 XXXXXXXXXXXXXXXXXXXXXXXXX X
	 XXXXXXXX XXX
	 XXXXXXXXX XXXXXXXXX
	 XXXXX XXXX
	 XXXX XXXX
	 XXXXXX XXXXXXX
	 XXXXXXX XXXXXXX
	 XXXXXXXXXXX XXXXX
	 XXXXXXXXXXXXXX XXXX
	 XXXXXXXXXXX XXXXXXXXX XXXXX
	 XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
X
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
	 XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
X
 XXXXXXX X
	 XXXXXXXX XX
	 XXXXXXXXX XXXXXXXXX
	 XXXXXXX XXXXX
X
 XXXXXXXXXXXXXXXXX X
	 XXXXXXXXXXX XXXXXXXXX XXXXX
	 XXXXXXXXXXXX XXXXXXXXXX
X
 XXXXXXXXXXXXXXXXX XXXXXXXXXX X
	 XXXXXXXXXXX XXXXXXXXX XXXXX
	 XXXXXXXXXXXX XXXXXXXXXX
X
 XXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXX XX
	 XXXXXX XXXXX
	 XXXXXXX XXXXX
	 XXXXXXXXX XXXXXXX
X
 XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX X
	 XXXXXXXX XX
	 XXXXXXXXXX XXXXXXXXXXXXXX
X
 XXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXX XX
	 XXXXX XXXXX
	 XXXXXX XXXXX
	 XXXXXXX XXXXX
	 XXXXXXXXXXXXXXXX XXXXXX
	 XXXXXXXXXXXX XXXXXXXXXX
X
 XXXXXXXXXXXXXXXXXXX X
	 XXXXX XX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
	 XXXXX XX
	 XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
		 XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
	X
X
 XXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
	 XXXXX XXXXX
	 XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
		 XXXXXXXXXXXXXXXXXXXXXXXX
	X
X
 XXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
	 XXXXX XXXXXX
	 XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
		 XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
	X
X
 XXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
	 XXXXX XXXXXX
	 XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXX
X
 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
	 XXXXX XXXXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
		 XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
	X
X
 XXXXXXXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXX XX
	 XXXXX XX
	 XXXXXX XXXXX
	 XXXXXXX XXXXX
X
 XXXXXXXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXXXXX XX
	 XXXXX XX
	 XXXXXXX XXXXX
	 XXXXXXXXXXX XXXXXX
	 XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXX XXXX XXXXX
	 XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
	 XXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXX
	 XXXXXXXX XX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXX X
		 XXXXXXXX XXXXX
	X
X
 XXXXXXXXXXXXXXX XXXX X
	 XXXXXXXX XXXX
X
 XXXXXXXXXXXX X
	 XXXXXXXXX XXXXXXXXX
	 XXXXXX XXXX
	 XXXXXXX XXXX
	 XXXXX XXXX
	 XXXXXX XXXXX
	 XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXX XXXX XXXXX
	 XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
	 XXXXXXXXXX XXXXXXXXXXXXXXXXX
	 XXXXXXXX XX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXX X
		 XXXXX XX
		 XXXXXXX XX
		 XXXXXX XXXXX
		 XXXXXXX XXXXXX
		 XXXXXXXXXXX XXXXXXX
		 XXXXXXXXXX XXXXXXXXXXXXXXXX
		 XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXX XXXX XXXXX
		 XXXXXXXX X XXXXX
	X
X
 XXXXXXXXXXXXXXXXXXXX X
	 XXXXXXXXXXXX XXXXXXXXXXXXXX
	 XXXXXXXXXX XXXXXXX
	 XXXXXXXXXXXXXX XXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXXXXX X
		 XXXXXXXXXXXX XXXXXX
		 XXXXXXXXXX XXXXXXX
	X
X
 XXXXXXXXXXXXXXXXX X
	 XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
	 XXXXXXXXXX XXXXXXX
	 XXXXXXXXXXXXXX XXXXXXX
	 XXXXXX XXXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXX X
		 XXXXXXXX XXXXX
	X
X
 XXXXXXXXXXXXXXXXX X
	 XXXXXXXX XX
	 XXXXXXXX XXXXXXXXXXXXX
	 XXXXXXXXX XXXXXXXXX
	 XXXXXXXX XXXXXXX
	 XXXXXXX XXXXXXXX
	 XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
	 XXXXXXXXXX XXXXXXX
	 XXXXXXXXXXXX XXXXXXX
X
 XXXXXX XXXXXXXXXXX XXXXXX X
	 XXXXXXXXXXXXXXXXX X
		 XXXXXXXX XXXXX
	X
X
 XXXXXXXXXXXXXXXXXXXXXXXX X
	 XXXXXXXX XXX
	 XXXXXXXX XXX
	 XXXXXXXXX XXXXXXXXX
	 XXXX XX
	 XXXXX XX
	 XXXXXX XXXXX
	 XXXXXXX XXXXX
	 XXXXXXXXXXX XXXXX
	 XXXXXXXXXXXXXXXXX XXX XXXXX
	 XXXXXXXXXX XXXXXXXXXXXXXXXX
	 XXXXXXXXXXX XXXXXXXXX XXXXX
	 XXXXXXXXXXXX XXXXXXXXXX
X
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
	 XXXXXXXXXX XXXXXXXXXXX
X

	XXXXXXXX
	XXXXXX
	
		
		XXXX XXXXXX XXXX XXXXX XXX
		XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXX
					 XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
							XX XXXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXX
					XXXX XXXXXXXXXXXXXX XXXXX XXX
					XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXX XXXX XXX
						XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
							XXXXXX XXXXXXXXX gettext(u'Ana Sayfa') XXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

								XXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
								XXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
								XXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
								XXXXX
							XXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX
						XXXX XXX XXXX XXXX XXX
					XXXXXX
					XXXX XXXXXXXXXXXXXX XXX XXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXX XXXXXX XXXX XXXXX XXX

		XXXX XXXXXX XXX
		XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXX XXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXX XXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXX XX XXXXXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX
										XXXX
									XXXXX
								XXXXX
								XXXX XXX XXXXXXX XXX
								XXXX XXXXXX XXX
								XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXX XXXXXXXXXX X XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXX X XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
								XXXXX
								XXXX XXX XXXXXX XXX
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
			XXXX XXX XXXXXX XXX
			
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XX XXXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXXXX                                      
												XXXX XXXX XXXX XXX
												XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Ana Sayfa') XXXX
									
														XXXXX
														XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Projelerimiz') XXXX
													
															XXX XXXXXXXXXXXXXXXXX
																	XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Devam eden projeler')  XXXXXXXXX
																	
																XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Planlanan projeler') XXXXXXXXX
															
																XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Tamamlanan projeler') XXXXXXXXX
																
															XXXXX
														XXXXX
													XXXXX
											
													XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBBXX gettext(u'Hakkımızda') XXXX
													
														XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
														XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'İletişim') XXXX
														XXXXX
														XXXX
															XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  X
                  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                  BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                  BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                    XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                    BB  BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXXXX
                  XXXXXXXXX

                  BBBB BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXXX
              XXXXXXXXX
                  BBBB BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXX
              XXXXXXXXX
                  BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXXX
              XXXXXXXXX
                  BBBBB
                  BBB BBBB BB BBBBBBBBB
                  BB BBBBBBBBB BB BBB
                      
                  BBBB
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX

                  XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    
                    
                    
                    
                  XXXX
                XXXXXXXXX
              BBBBB

                  BBBBBB

                XXXXXXXXX
															
														XXXXX
												XXXXX
												XXXX XXX XXXX XXXX XXX
											XXXXXX
										XXXXXX
									XXXXXX
								XXXXXX
							
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXX
		XXXX XXX XXXXXX XXX
	XXXX XXXX XXXXXXX  XXXX XXX
	XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
	XXXXXX
		XXXX XXX XX XXXX XXXXXXX  XXX

		XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			XXX XXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX
			  XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XX
				  XXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'MARMARA EVLERİ KONUT YAPI KOOPERATİFİ') XXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXXX					
						 gettext(u'Kooperatifimiz İstanbul, Arnavutköy de İstanbul Havaalanına 5,6 km mesafede, deniz ve Kanal İstanbul manzaralı 16.106 m2 arsanın alımı için protokol imzalamıştır.') XXXX
						
					XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X gettext(u'Projeyi Görüntüle') X XXXX
					
				  XXXXXX
				XXXXXX
			  XXXXXX
			  XXXX XXXXXXXXXXXX XXXXXXX XX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XX
				  XXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX	 gettext(u'GERDER PROJESİ') XXXXX
				
					XX XXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u"( 4.600 m2 ) dönüm hazine arazisinde toplu konut veya Üniversite kampüslari tasarlanıyor. Bunların her ikisi'de yapılaşmayı hızlandıracaktır.")  XXXX
	
					XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Projeyi Görüntüle') 
XXXX
				  XXXXXX
				XXXXXX
			  XXXXXX
			  XXXX XXXXXXXXXXXX XXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XX
				  XXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kanal İstanbul Projesi') XXXXX
					
					XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"Kanal-İstanbul Projesi, İstanbul Avrupa Yakası'nın kuzeyinde Karadeniz'e kıyısı olan 3. Köprü (Yavuz Sultan Selim Köprüsü) bağlantı yolu üzerinde yer alan bir gayrimenkul projesidir. Proje, yaklaşık 450.000 m²'lik geniş bir alanda konumlanmıştır ve komşuları Çatalca, Esenyurt ve Başakşehir içlerinde yer almaktadır.") XXXX
					
					XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X gettext(u'Projeyi Görüntüle') 
XXXX
				  XXXXXX
				XXXXXX
			  XXXXXX
			  XXXX XXXXXXXXXXXX XXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XX
				  XXXXXX
				  XXXX XXXXXXXXXXXXXXXXXXXX
					XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kanal Ankara Projesi') XXXXX
					
					XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXX XX   XX XXX XXXXXX XX XXX XXXX XX XX XXXX XXXXX XXXXXXXXXXXXX
						XXXXXXX XXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Projeyi Görüntüle') 
XXXX
				  XXXXXX
				XXXXXX
			  XXXXXX
			XXXXXX
		  XXXXXX
		  
		XXXX XXXXXXXX XXXXXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX
						XXXX XXXXXXX XXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
							XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Projelerimizi İnceleyin') XXXXX
							

						XXXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXX
				
					XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXX XXXXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXX XXXXXX XXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXX
										XXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXX XXXXXX XXXXXXX XXX
							XXXX XXXXX XXXXXX XXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXX
										XXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXX XXXXXX XXXXXXX XXX
						XXXXXX
						XXXX XXX XXXXX XXXXXXX XXX
					XXXXXX
				XXXXXX
		
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXXXXX XXXXXXX XXX

		XXXX XXXXX XXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXX XXXXX XXXXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX
									XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
								XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'12 Yılı aşkın')  XXXXXX gettext(u'Tecrübe') XXXXXXXXXXXX
								XXXXXX
							XXXXXX
						XXXXXX
						XXXX XXX XXXXX XXXXX XXXXX XXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXX XXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Hakkımızda') XXXXXXX
								XXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Geleceğe Değer Katmak İçin Buradayız') XXXXX
								
							XXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
								XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gayrimenkuldeki uzmanlığımız ve müşteri odaklı yaklaşımımızla Land Invest Gayrimenkul olarak, sektörde önde gelen bir gayrimenkul şirketiyiz. Misyonumuz, müşterilerimize kaliteli gayrimenkul hizmetleri sunarken, onların ihtiyaçlarını ve beklentilerini aşmaktır.') XXXX
								
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
									XXX gettext(u'Land Invest Gayrimenkul olarak, sektördeki liderliğimizi sürdürmek ve müşterilerimize en iyi hizmeti sunmak için sürekli olarak kendimizi geliştiriyoruz') XXXX
									
								XXXXXX
			
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXX XXXX XXX

		
		
		XXXX XXXXXXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
							XX XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'4 Aşamada') XXXX
							XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Neden Biz?') XXXXX
						XXXXXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
										XXXXXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
									XXXXXX
								XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Geniş Portföy')  XXXXX
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Geniş bir portföy sunuyoruz.') XXXX
									
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
										XXXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
									XXXXXX
								XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Uzmanlık ve Deneyim') XXXXX
									
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sektörde uzman ve deneyimli bir ekibiz.') XXXX
									
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
										XXXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
									XXXXXX
								XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Müşteri Memnuniyet') XXXXX
									
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sizler bizim önceliğimizsiniz') XXXX
									
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXX XXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
										XXXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
									XXXXXX
								XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Etkili İletişim') XXXXX
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Doğru iletişim önceliğimizdir') XXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXXXX XXXXXX XXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXXXXX XXX

			
		XXXX XXX XXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'SSS') XXXXXXX
							XXXXXX
							XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sık Sorulan Sorular') XXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
							XXXX XXX XXXXXX XXXXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sizinle çalışmanın avantajları nelerdir?') XXXXXXXXX
									
								XXXXX
								XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Uzmanlık, deneyim, geniş portföy, müşteri memnuniyeti odaklı hizmetler ve profesyonel iletişim gibi avantajlarımız bulunmaktadır.') XXXXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXXXXXXX XXX

							XXXX XXXXXX XXXXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'Referanslarınızı paylaşabilir misiniz?') XXXXXXXXX
						
								XXXXX
								XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Tabiki! Bir telefon kadar yakınız.') XXXXXX
									
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXXXXXXX XXX

							XXXX XXXXXX XXXXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Emlak danışmanlarınızın uzmanlık alanları nelerdir?') XXXXXXXXX
									
								XXXXX
								XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Emlak danışmanlarımız farklı uzmanlık alanlarına sahip olup, konut, ticari mülkler veya yatırım fırsatları gibi alanlarda uzmanlaşmışlardır.') XXXXXX
									
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXXXXXXX XXX
							XXXX XXXXXX XXXXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'Sizden hizmet almanın güvencesi nedir?') XXXXXXXXX
								XXXXX
								XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Firmamız, sektördeki deneyimi, müşteri memnuniyetine verdiği önem ve uzman kadrosuyla size güvenilir bir hizmet sunmanın garantisini vermektedir.') XXXXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXXXXXXX XXX
						XXXXXX	
					XXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXX XXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									 gettext(u'Sizin İçin Buradayız') 
								XXXXX
							XXXXXX
						XXXXXX
						XXXX XXX XXXXXXX XXX XXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXX XXXX XXX

		XXXX XXXX XXXX XXX
		XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Son yazılarımız') XXXXX
								
							XXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXX
						BBB B BB BBBBBBBBBBBBB
						XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
							XXXX XXXXXX XXXX XXX
							XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
									XX XXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXXXXXX XXXXXX XXXXXXXXXXXX
									XXXX XXXX XXXXXXX XXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
											XXX XXXXXXXXXXXXXXX
												XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
												XXXXXX
												XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
											XXXXX
										XXXXX
										XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
											XX XXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
												XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX XXXXXX XXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XX XX XXXXXXXXXX XX XX XXXXXXX XX XXXXX XXXXXXX XXXXXXX X XX XXXXXXXXX X XXXXXXX XXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
												XXXXXX
											XXXX
										XXXXXX
									XXXXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXX XXX
						XXXXXX	
						BBBBBB 
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXX XXXX XXX

	

    XXXX XXXXXX XXX
			XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXX XXXX XXX
							XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sizin İçin Buradayız') XXXXXXX
									
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bültenimize Kaydol') XXXXX
									
								XXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kaydol') XXXXXXXXXXXXXXXX
								XXXXXXX
							XXXXXX
							XXXX XXX XXXXXXXXX XXXX XXX
						XXXXXX
					XXXXXX	
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
										XXXX XXXXXX XXXXXX XXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXX
											XXXXXX
											XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gayrimenkulde Uzmanlık, Müşteri Memnuniyeti İlkesiyle') XXXX
											
											XXXX XXXXXX XXX
											XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXX XXXXXXXXXX X XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXX X XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
											XXXXX
											XXXX XXX XXXXXX XXX
										XXXXXX
										XXXX XXX XXXXXX XXXXXX XXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
										XXXX XXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXX XXX
												XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sayfalar') XXXXX
													XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Ana Sayfa') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Projelerimiz') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Hakkımızda') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Blog') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'İletişim') XXXXXXXXX
													XXXXX
												XXXXXX
												XXXX XXX XXXXXX XXXXXX XXX
											XXXXXX

											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXX XXX
												XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'İletişime Geç!') XXXXX
													XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XX XXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX
																XXXXXXX XXXXXXXXXXXXXXXX
														XXXXX
													XXXXXX
												XXXXXX
												XXXX XXX XXXXXX XXXXXX XXX
											XXXXXX
										XXXXXX
									XXXXXX
								XXXXXX
							XXXXXX	
						XXXXXX
					XXXXXX		
				XXXXXX

			XXXXXXXXX
			XXXX XXX XXXXXX XXX	
	
			XXXX XXXXXX XXX XXX
			XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Başa Dön') XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
			
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX

			XXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXX XXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXX XXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
	
			XXXXXXXX
				XX XXXX XXXXXXXX XXXXXX XX
				XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
					XXXXXXXXX X 
						XXXXXX XXXXX
					XX
					XXXXXXXXXXX X
					  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					XX
					XXXXXXX XXXXXXX
					XXXXXXXXXXX XXXXX
					XXXXXXXXX XXXXX
					XXXXX XXXXX
					XXXXXXXXXXX XXXXX
					XXXXXX XXXX
					XXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXXX XXXXXX
					XXXXXXXXXXX X
						XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXXXXXX
						XXXXXXXXXX XXXXX
					XX
					XXXXXXXXXXXXXX XXXX
				XXX	
				XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  
  XXX XXXXXXX X XXXXXXXXXXXXX
      XXXXXXXXX X XXXXXXXXXXXXXXXX
      XXXX X XX
      XXXXXXXX X XX
      XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX X XXXXXX
      XXXXXXXX X XXXX
      XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX X XXXXX
      XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
  
  XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXX X X XX X X XXXXXXXXXXXXXX XXXX X
      XXX XXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XX XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    X
  XX
  
  XXXXXXXXXXXXXXXX
  
  XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX
  
  XXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX
      XX XXXXXXXXX X XXXXXXXXXXXX XXXXXXXX X XX
      XXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX
  XX
  
  XXXXXXXXXXXX
  
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXXXXXX X
      XXXXXXXXX X XXXXX
      XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX X XXXXXX
      XX XXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
    XXXX X XX
    XXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXX X
    XX XXXXXXXXXXX XXXXXXX
    XX XXXXXXXXX X XX XXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXX X
    XX XXXXXXXXXXX XXXXXXX
    XX XXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXX X XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX X XXXXXXXXXXXXXXXXXX
    XXXX X XX
    
    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX X
      XXX X X XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX X XXXXXXX X XX X XXXX X XXX
      XX XXXXXXXXXXX XX XXXX X XX XX XXXXXXXXX XXX XXXXXXXXXXX XX XXXX X XXX XXXX XX XX
      XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX X XXXXXXX XXXXXXXXXXX
    XXX
  XXX
  
  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXX
    XX XXXXXXX X
      XXXXXXXXXXXXXXXXXXX
      XXXXXXX
    X
    XX XXXXX X XX XX XXXX X XX X
      XXXXXXXXXXXXXXX
      XXXXXXX
    X
    XX XXXXX XX XXX X
      XXXXXXXXXXXXXXX
    X
    XX XXXXX XX XX X
      XXXXXXXXXXXXXXXX
    X
  XXX
  
  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX
    X XXXX X
      XXXXXXXXXXXXXXXX
    X
  XXX
  
  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
  XXX
  
XXX
			 XXXXXXXXX
		XXXXXXX
	XXXXXXX