BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
	XXXXXX
		XXXX XXXX XXXX XXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
		XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		
		XXXX XXXX XXXXX XXX
		XXXXXXXXXXXXX X XXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX
		
		XXXX XXX XXXX XXX
		XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
		
		XXXX XXXXXX XXXXX XXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 

		XXXX XXXXXXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXXXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXX XXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXX XXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXX XXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXX XX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		
		XXXX XXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

		
	XXXXXXX
	XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXX
	XXXXXXXX
	XXXXXX

		
		XXXX XXXXXX XXXX XXXXX XXX
		XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXX
					 XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XX XXXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXX
					XXXX XXXXXXXXXXXXXX XXXXX XXX
					XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXX XXXX XXX
						XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
								XXXXXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Ana Sayfa') XXXX
		
							XXXXX
							XXX XXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX
		
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							
							XXXXX
							XXX XXX XXXXXXXBBB BBBBBBBBBBBBXXXXXXXXXXXXXXXX
						
							XXXXX
							XXX XXX XXXXXXXBBB BBBBBBBBBBBXXXXXXXXXX
							XXXXX
							XXX XXX XXXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXX
							XXXXX
						XXXXX
						XXXX XXX XXXX XXXX XXX
					XXXXXX
					XXXX XXXXXXXXXXXXXX XXX XXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXX XXXXXX XXXX XXXXX XXX

		XXXX XXXXXX XXX
		XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXX XXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXX XXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXX XX XXXXXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX
										XXXX
									XXXXX
								XXXXX
								XXXX XXX XXXXXXX XXX
								XXXX XXXXXX XXX
								XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXX XXXXXXXXXX X XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXX X XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
								XXXXX
								XXXX XXX XXXXXX XXX
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
			XXXX XXX XXXXXX XXX
			
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XX XXXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXXXX                                      
												XXXX XXXX XXXX XXX
												XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
															XXXXXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Ana Sayfa') XXXX
									
														XXXXX
														XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Projelerimiz') XXXX
															XXX XXXXXXXXXXXXXXXXX
																		XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Devam eden projeler')  XXXXXXXXX
																	
																XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Planlanan projeler') XXXXXXXXX
															
																XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Tamamlanan projeler') XXXXXXXXX
															XXXXX
														XXXXX
													XXXXX
											
														XXX XXX XXXXXXXBBB BBBBBBBBBBBBXX gettext(u'Hakkımızda') XXXX
													
														XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
														XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'İletişim') XXXX
														XXXXX
													XXXX
															XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  X
                  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                  BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                  BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                    XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                    BB  BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXXXX
                  XXXXXXXXX

                  BBBB BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXXX
              XXXXXXXXX
                  BBBB BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXX
              XXXXXXXXX
                  BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXXX
              XXXXXXXXX
                  BBBBB
                  BBB BBBB BB BBBBBBBBB
                  BB BBBBBBBBB BB BBB
                      
                  BBBB
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX

                  XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    
                    
                    
                    
                  XXXX
                XXXXXXXXX
              BBBBB

                  BBBBBB

                XXXXXXXXX
															
														XXXXX
												XXXXX
												XXXX XXX XXXX XXXX XXX
											XXXXXX
										XXXXXX
									XXXXXX
								XXXXXX
						
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXX
		XXXX XXX XXXXXX XXX
	XXXX XXXX XXXXXXX  XXXX XXX
		XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
	XXXXXX
		XXXX XXX XX XXXX XXXXXXX  XXX
		BBB B BB BBBBBBBBBBBBBBB
		XXXX XXXXXXXXXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXX
					XXXX XXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXX	
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXXXXXXXX XXX
 XXXX XXXXXXXX XXXXXX XXXXXX XXX
 XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
							XXX XXXXXXXXXXXXXXX
								XXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
										
										XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX   XXXXXXXXXXX XXXXXXXX

									XXXXXX
								XXXXX
								
								BBB BB  BB BBBBB
								BB BBBBBBBBBBBBBBBBBBBBB	
										
											
								XXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
										
										XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX   XXXXXXXXXXX XXXXXXXX
										
									XXXXXX
								XXXXX


								BBBB
								BBBBB
								BBBBBB
								
							XXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
								XXX XXXXXXXXXXXXXXX
									XXXX
										XXXX XXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX  XXXXXXXXXXX XXXXXXXX
										XXXXXX
										
									XXXXX
								BBB BB  BB BBBBB
								BB BBBBBBBBBBBBBBBBBBBBB	
										
											
								XXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX  XXXXXXXXXXX XXXXXXXX
									XXXXXX
									
								XXXXX


								BBBB
								BBBBB
								BBBBBB
								
									
								XXXXX
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXXXXXX
XXXX XXX XXXXXXXX XXXXXX XXXXXX XXX
       

		XXXX XXXXXXXX XXXXXXX XXX
        XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX                                                   
                    XXXX XXXXXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
							XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
								 gettext(u'Proje Detayları') 
							XXXX
							XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Proje Planı') XXXX
							

							XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Proje Videosu') XXXX
							

							XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Proje Lokasyonu') XXXX
							
						XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX  XXXXXXXX XXXXXXX XXX
                                XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										
                                        XXX FFFF XXXX 
                                       
                                        XXXX XXXXX XXXXXXXX XXX
                                    XXXXXX
                                XXXXXX
                                XXXX  XXX XXXXXXXX XXXXXXX XXX
                                XXXX  XXXXX XXXXX XXX
                                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXX XXXXXXXXX XXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'Plan1') XXXXXXXXX
                                                XXXXX
                                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
                                                        XXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                            gettext(u'Plan İçeriği') 
                                                        XXXXXX
                                                    XXXXXX
                                                XXXXXX
                                            XXXXXX
                                            XXXX XXX XXXXXX XXXXXXXXX XXX
                                            XXXX XXXXXX XXXXXXXXX XXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Plan2') XXXXXXXXX
                                                XXXXX
                                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
															XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
                                                        XXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                            gettext(u'Plan İçeriği') 
                                                        XXXXXX
                                                    XXXXXX
                                                XXXXXX
                                            XXXXXX
                                            XXXX XXX XXXXXX XXXXXXXXX XXX
											XXXX XXXXXX XXXXXXXXX XXX
											 XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'Plan3') XXXXXXXXX
                                                XXXXX
                                                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
															XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
                                                        XXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                            gettext(u'Plan İçeriği') 
                                                        XXXXXX
                                                    XXXXXX
                                                XXXXXX
                                            XXXXXX
                                            XXXX XXX XXXXXX XXXXXXXXX XXX
											 XXXX XXXXXX XXXXXXXXX XXX
											 XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X gettext(u'Plan4') XXXXXXXXX
                                                XXXXX
                                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
															XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
                                                        XXXXXX
                                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                            gettext(u'Plan İçeriği') 
                                                        XXXXXX
                                                    XXXXXX
                                                XXXXXX
                                            XXXXXX
                                            XXXX XXX XXXXXX XXXXXXXXX XXX
                                        XXXXXX	
                                    XXXXXX
                                XXXXXX
                                XXXX  XXX XXXXX XXXXX XXX
                                XXXX  XXXXXXXX XXXXX XXX
                                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXX XXXXXXXX XXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                           XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXX
                                           XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
													XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXXX XX XX XXXXXXX XX XXXXX XXXXXXX XXXXXXX X XX XXXXXXXXX X X XXXXXXX X XXXX XXXXXXX XXXXXXX XX XX XXXX XXXXXXXXXXXXXXXX
															XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
														XXXXXX
														XXXXXX gettext(u'Videoyu Oynat') XXXXXXX
													XXXXXX
												XXXX
                                           XXXXXX
                                          
                                        XXXXXX
                                        XXXX XXX XXXXX XXXXXXXX XXX
                                    XXXXXX
                                    
                                XXXXXX
                                XXXX  XXX XXXXXXXX XXXXX XXX
                                XXXX  XXXXXXXX XXX XXX
                                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
										XXXX XXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
													XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX X XXXXXX XXXXXXXXX X XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXX
															XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XX
														XXXXXX
													XXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Adres') XXXXX
													XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXXX
											XXXXXX
											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
													XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXXX
											XXXXXX
										XXXXXX
                                       XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        XXXXXX
                                    XXXXXX
                                XXXXXX
                                XXXX  XXX XXXXXXXX XXX XXX
                       
                            XXXXXX
                        XXXXXX
                    XXXXXX
					BBBBBB 
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX
                        XXXX XXXXXXXX XXXXX XXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'İletişime Geçin') XXXXX
                            XXXX XXXXXXXX XXXXXXX XXX
                            XXXX XXX XXXXXXXX XXXXXXX XXX
                            XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gönder') XXXXXXXXXXXXXXXX
                            XXXXXXX
                        XXXXXX
                        XXXX XXX XXXXXXXX XXXXX XXXX XXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
		XXXX XXX XXXXXXXX XXXXXXX XXX

XXXX XXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXX XXXX XXX
							XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sizin İçin Buradayız') XXXXXXX
									
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bültenimize Kaydol') XXXXX
									
								XXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kaydol') XXXXXXXXXXXXXXXX
								XXXXXXX
							XXXXXX
							XXXX XXX XXXXXXXXX XXXX XXX
						XXXXXX
					XXXXXX	
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
										XXXX XXXXXX XXXXXX XXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXX
											XXXXXX
											XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gayrimenkulde Uzmanlık, Müşteri Memnuniyeti İlkesiyle') XXXX
											
											XXXX XXXXXX XXX
											XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXX XXXXXXXXXX X XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXX X XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
											XXXXX
											XXXX XXX XXXXXX XXX
										XXXXXX
										XXXX XXX XXXXXX XXXXXX XXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
										XXXX XXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXX XXX
												XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sayfalar') XXXXX
													XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Ana Sayfa') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Projelerimiz') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Hakkımızda') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Blog') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'İletişim') XXXXXXXXX
													XXXXX
												XXXXXX
												XXXX XXX XXXXXX XXXXXX XXX
											XXXXXX

											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXX XXX
												XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'İletişime Geç!') XXXXX
													XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XX XXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX
																XXXXXXX XXXXXXXXXXXXXXXX
														XXXXX
													XXXXXX
												XXXXXX
												XXXX XXX XXXXXX XXXXXX XXX
											XXXXXX
										XXXXXX
									XXXXXX
								XXXXXX
							XXXXXX	
						XXXXXX
					XXXXXX		
				XXXXXX

			XXXXXXXXX
XXXX XXX XXXXXX XXX	

		XXXX XXXXXX XXX XXX
		XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
		
		XXXX XXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XX XXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXXX XXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXX XXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXX XXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXX XXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXX XX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX
				  XXXXXXXXXXXXXXXXXXXXX
				    XXXXXXXXXX XXXXXXX
					XXXXXXXXXXX XXXXXX 
					XXXXXXXXXXXXX XXXXXX    
				    XXXXXX XXXXXXXXXXXXXXXXX
				      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				    X
				  XXX
				 XXXXXXXXXXXXXXXXXXXXX
				    XXXXXXXXXX XXXXXXXX
				    XXXXXXXXXXXXXX XXXXX
				    XXXXXXXXXX XXXX
					XXXXXXXXXXX XX 
				    XXXXXXXXXX XXXXXX
				    XXXXXXXXXXX XXXXX
				    XXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXX XXXXXX 
					XXXXX XX 
					XXXXXXXXXXXXXX XXXXXX
					XXXXXXXXXX XXXXXX 
					XXXXXXXXXXXXXXX XXXX
				  XXX
				XXX
		XXXXXXXXX
	XXXXXXX
XXXXXXX