
BBBB BBBBBB
BBBB BBBB


XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
	XXXXXX
		XXXX XXXX XXXX XXX
		XXXXX XXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX
		XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
		XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		
		XXXX XXXX XXXXX XXX
		XXXXXXXXXXXXX X XXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX
		
		XXXX XXX XXXX XXX
		XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
		
		XXXX XXXXXX XXXXX XXX
		XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 

		XXXX XXXXXXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXXXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXX XXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXX XXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXX XXXXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
		XXXX XXXXXX XX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		
		XXXX XXXX XXX XXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
		XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

		XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

		
	XXXXXXX
	XXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXX
	XXXXXXXX
	XXXXXX
	
		
		XXXX XXXXXX XXXX XXXXX XXX
		XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
						XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXX XXX
					 XXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
							XX XXXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX
						XXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXX
					XXXX XXXXXXXXXXXXXX XXXXX XXX
					XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
						XXXX XXXX XXXX XXX
						XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
							XXXXXX XXXXXXXXXXXX XXXXXXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

								XXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
								XXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
								XXXXX
							XXXXX
							XXX XXX XXXXXXXXXXXXXXXXX
								XXX XXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
								XXXXX
							XXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX
						XXXX XXX XXXX XXXX XXX
					XXXXXX
					XXXX XXXXXXXXXXXXXX XXX XXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXX XXXXXX XXXX XXXXX XXX

		XXXX XXXXXX XXX
		XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXX XXX
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXX XXX
								XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXX XX XXXXXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX
											XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX
										XXXX
									XXXXX
								XXXXX
								XXXX XXX XXXXXXX XXX
								XXXX XXXXXX XXX
								XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXX XXXXXXXXXX X XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXX X XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
									XXXX
										XX XXXXXXXXX
											XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
												XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXX
										XXXX
									XXXXX
								XXXXX
								XXXX XXX XXXXXX XXX
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
			XXXX XXX XXXXXX XXX
			
			XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XX XXXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXXXX                                      
												XXXX XXXX XXXX XXX
												XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX
															XXXXXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Ana Sayfa') XXXX
									
														XXXXX
														XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Projelerimiz') XXXX
															XXX XXXXXXXXXXXXXXXXX
																		XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Devam eden projeler')  XXXXXXXXX
																	
																XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Planlanan projeler') XXXXXXXXX
															
																XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Tamamlanan projeler') XXXXXXXXX
															XXXXX
														XXXXX
													XXXXX
											
														XXX XXX XXXXXXXBBB BBBBBBBBBBBBXX gettext(u'Hakkımızda') XXXX
													
														XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
														XXXXX
														XXX XXX XXXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'İletişim') XXXX
														XXXXX
													XXXX
															XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  X
                  BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                  BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                  BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                    XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                    BB  BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXXXX
                  XXXXXXXXX

                  BBBB BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXXX
              XXXXXXXXX
                  BBBB BBB BB BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXX
              XXXXXXXXX
                  BBBB
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXXXX
              XXXXXXXXX
                  BBBBB
                  BBB BBBB BB BBBBBBBBB
                  BB BBBBBBBBB BB BBB
                      
                  BBBB
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX

                  XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    
                    
                    
                    
                  XXXX
                XXXXXXXXX
              BBBBB

                  BBBBBB

                XXXXXXXXX
															
														XXXXX
												XXXXX
												XXXX XXX XXXX XXXX XXX
											XXXXXX
										XXXXXX
									XXXXXX
								XXXXXX
						
							XXXXXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXX
		XXXX XXX XXXXXX XXX
	XXXX XXXX XXXXXXX  XXXX XXX
		XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
	XXXXXX
		XXXX XXX XX XXXX XXXXXXX  XXX

		XXXX XXXXXXXXXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXX XXX
					XXXX XXXXXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Projelerimiz') XXXXX
						XXXXXX	
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXXXXXXXX XXX
		
		XXXX XXXXXXXX XXX
		XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX
						XXXX XXXXXXXX XXX XXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXX XXXXXXXXXXXX XXXXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX X
									XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Ara') XXXXXXXXXXXXXXXX
								XXXXXXX
								XXXX XXXX XXXXXXX XXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Proje') XXXX
								XXXXXX
								XXXX XXX XXXX XXXXXXX XXX
							XXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
									XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
										XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXXX
										XXXXXX
									XXXX
									XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
										XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
											XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
										XXXXXX
									XXXX
								XXXXXX
							XXXXXX
						XXXXXX
						XXXX XXX XXXXXXXX XXX XXX
					XXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
							XXXX XXXXXX XXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Ülke') XXXXX
									XXXX XXXXXXXXXXXXXXXXXXX
										XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
											XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXXXXXXXX
									XXXXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXXXXX XXX
							XXXX XXXXXX XXXXXXX XXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Şehir') XXXXX
									XXXX XXXXXXXXXXXXXXXXXXX
										XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
											XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
										XXXXXXXXX
									XXXXXX
								XXXXXX
							XXXXXX
							XXXX XXX XXXXXX XXXXXXX XXX

	
							XXXX XXX XXXXXX XXXXXXX XXX
						XXXXXX
		
					XXXXXX
					XXXX XXXXXXXXXXXXXXX XXXXXXXX
						XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
							XXXX XXXX XXX XXX
							XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
								XXXX XXXXXXXXXXXX
									BBB B BB BBBBBBB
									XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX X
										XXXX XXXXXX XXXXXXXXXXX
									
										XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
											XXXX XXXXXXXX XXXXXXX
											XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXXXX
											XXXXXX
											XXXX XXXXXXXX XXXXXXX
										
											XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXXX
												XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXXXX
												XXXXXX
											XXXXXX
										XXXXXX
										 
										XXXX XXX XXXXXX XXXXXXXXXXX
									XXXXXX
									BBBBBB  
								
								XXXXXX
								XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

									BB BBBBBBBBBBBBBBBBBBBB
									  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
									
									  BB BBBBBBBBBBBBBB B B
									
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
										BB BBBBBBBBBBBBBB B B
										  XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										BBBBB
									  BBBBB
									BBBBB
									
									BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
									  BB BBBBBBBBBBBBBB BB BBB
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBB BBB B BBBBBBBBBBBBBBBBBBBBBBB BBB BBB B BBBBBBBBBBBBBBBBBBBBBB
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBBB
									BBBBBB
									
									BB BBBBBBBBBBBBBBBB
									  BB BBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
										XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBB BBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
										XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
									  BBBBB
									
									  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
									BBBBB
								XXXXX
							XXXXXX
						
							XXXX XXX XXXX XXX XXX
							XXXX XXXX XXX XXX
							XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

								XXXX XXXXXXXXXXXX
								
									BBB B BB BBBBBBBB
									XXXX XXXXXXXXXXXXX XXXXXXXXXXX
										XXXX XXXXXX XXXXXXXXXXX
										XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXXXX XXXXXXX
											XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXX XXXXXXXX
											XXXXXX
											XXXX XXXXXXXX XXXXXXX
											XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXXX
												XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
												XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
													XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
												XXXXXX
											XXXXXX
										XXXXXX
										XXXX XXX XXXXXX XXXXXXXXXXX
									XXXXXX
									BBBBBB  
								XXXXXX
					
							XXXXXX
							XXXX XXX XXXX XXX XXX
						XXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXXXXXX
		XXXX XXX XXXXXXXX XXX



       XXXX XXXXXX XXX
			XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
				XXXXXX
				XXXX XXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXX XXXX XXX
							XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Sizin İçin Buradayız') XXXXXXX
									
									XXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Bültenimize Kaydol') XXXXX
									
								XXXXXX
								XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
									XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kaydol') XXXXXXXXXXXXXXXX
								XXXXXXX
							XXXXXX
							XXXX XXX XXXXXXXXX XXXX XXX
						XXXXXX
					XXXXXX	
					XXXX XXXXXXXXXXXX
						XXXX XXXXXXXXXXXXXXX
							XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
								XXXX XXXXXXXXXXXX
									XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
										XXXX XXXXXX XXXXXX XXX
										XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
												XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXX
											XXXXXX
											XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gayrimenkulde Uzmanlık, Müşteri Memnuniyeti İlkesiyle') XXXX
											
											XXXX XXXXXX XXX
											XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXX XXXXXXXXXX X XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXX X XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXX XXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
												XXXX
													XX XXXXXXXXX
														XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XX XXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
															XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXXXXX
													XXXX
												XXXXX
											XXXXX
											XXXX XXX XXXXXX XXX
										XXXXXX
										XXXX XXX XXXXXX XXXXXX XXX
									XXXXXX
									XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
										XXXX XXXXXXXXXXXX
											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXX XXX
												XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sayfalar') XXXXX
													XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Ana Sayfa') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Projelerimiz') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Hakkımızda') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Blog') XXXXXXXXX
														XXXXXX XXXXXXXBBB BBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'İletişim') XXXXXXXXX
													XXXXX
												XXXXXX
												XXXX XXX XXXXXX XXXXXX XXX
											XXXXXX

											XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
												XXXX XXXXXX XXXXXX XXX
												XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
													XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'İletişime Geç!') XXXXX
													XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
														XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XX XXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXX
																XXXXXXX XXXXXXXXXXXXXXXX
														XXXXX
													XXXXXX
												XXXXXX
												XXXX XXX XXXXXX XXXXXX XXX
											XXXXXX
										XXXXXX
									XXXXXX
								XXXXXX
							XXXXXX	
						XXXXXX
					XXXXXX		
				XXXXXX

			XXXXXXXXX
			XXXX XXX XXXXXX XXX	
	
			XXXX XXXXXX XXX XXX
			XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Başa Dön') XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXX XXXXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXX XXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
			XXXX XXXX XX XXX
			XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
	
			XXXXXXXX
				XX XXXX XXXXXXXX XXXXXX XX
				XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
					XXXXXXXXX X 
						XXXXXX XXXXX
					XX
					XXXXXXXXXXX X
					  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					XX
					XXXXXXX XXXXXXX
					XXXXXXXXXXX XXXXX
					XXXXXXXXX XXXXX
					XXXXX XXXXX
					XXXXXXXXXXX XXXXX
					XXXXXX XXXX
					XXXXXXXXXXXXX XXX
					XXXXXXXXXXXXXXX XXXXXX
					XXXXXXXXXXX X
						XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXXXXXX
						XXXXXXXXXX XXXXX
					XX
					XXXXXXXXXXXXXX XXXX
				XXX	
	
			 XXXXXXXXX
		XXXXXXX
	XXXXXXX